/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ResourceLibrary } from "./ResourceLibrary";
import { ResourceLibraryCountArgs } from "./ResourceLibraryCountArgs";
import { ResourceLibraryFindManyArgs } from "./ResourceLibraryFindManyArgs";
import { ResourceLibraryFindUniqueArgs } from "./ResourceLibraryFindUniqueArgs";
import { DeleteResourceLibraryArgs } from "./DeleteResourceLibraryArgs";
import { ResourceLibraryService } from "../resourceLibrary.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ResourceLibrary)
export class ResourceLibraryResolverBase {
  constructor(
    protected readonly service: ResourceLibraryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ResourceLibrary",
    action: "read",
    possession: "any",
  })
  async _resourceLibrariesMeta(
    @graphql.Args() args: ResourceLibraryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ResourceLibrary])
  @nestAccessControl.UseRoles({
    resource: "ResourceLibrary",
    action: "read",
    possession: "any",
  })
  async resourceLibraries(
    @graphql.Args() args: ResourceLibraryFindManyArgs
  ): Promise<ResourceLibrary[]> {
    return this.service.resourceLibraries(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ResourceLibrary, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ResourceLibrary",
    action: "read",
    possession: "own",
  })
  async resourceLibrary(
    @graphql.Args() args: ResourceLibraryFindUniqueArgs
  ): Promise<ResourceLibrary | null> {
    const result = await this.service.resourceLibrary(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ResourceLibrary)
  @nestAccessControl.UseRoles({
    resource: "ResourceLibrary",
    action: "delete",
    possession: "any",
  })
  async deleteResourceLibrary(
    @graphql.Args() args: DeleteResourceLibraryArgs
  ): Promise<ResourceLibrary | null> {
    try {
      return await this.service.deleteResourceLibrary(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
