/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Geolocation } from "./Geolocation";
import { GeolocationCountArgs } from "./GeolocationCountArgs";
import { GeolocationFindManyArgs } from "./GeolocationFindManyArgs";
import { GeolocationFindUniqueArgs } from "./GeolocationFindUniqueArgs";
import { DeleteGeolocationArgs } from "./DeleteGeolocationArgs";
import { GeolocationService } from "../geolocation.service";
@graphql.Resolver(() => Geolocation)
export class GeolocationResolverBase {
  constructor(protected readonly service: GeolocationService) {}

  async _geolocationsMeta(
    @graphql.Args() args: GeolocationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Geolocation])
  async geolocations(
    @graphql.Args() args: GeolocationFindManyArgs
  ): Promise<Geolocation[]> {
    return this.service.geolocations(args);
  }

  @graphql.Query(() => Geolocation, { nullable: true })
  async geolocation(
    @graphql.Args() args: GeolocationFindUniqueArgs
  ): Promise<Geolocation | null> {
    const result = await this.service.geolocation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Geolocation)
  async deleteGeolocation(
    @graphql.Args() args: DeleteGeolocationArgs
  ): Promise<Geolocation | null> {
    try {
      return await this.service.deleteGeolocation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
