/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { MentorshipProgram } from "./MentorshipProgram";
import { MentorshipProgramCountArgs } from "./MentorshipProgramCountArgs";
import { MentorshipProgramFindManyArgs } from "./MentorshipProgramFindManyArgs";
import { MentorshipProgramFindUniqueArgs } from "./MentorshipProgramFindUniqueArgs";
import { DeleteMentorshipProgramArgs } from "./DeleteMentorshipProgramArgs";
import { MentorshipProgramService } from "../mentorshipProgram.service";
@graphql.Resolver(() => MentorshipProgram)
export class MentorshipProgramResolverBase {
  constructor(protected readonly service: MentorshipProgramService) {}

  async _mentorshipProgramsMeta(
    @graphql.Args() args: MentorshipProgramCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [MentorshipProgram])
  async mentorshipPrograms(
    @graphql.Args() args: MentorshipProgramFindManyArgs
  ): Promise<MentorshipProgram[]> {
    return this.service.mentorshipPrograms(args);
  }

  @graphql.Query(() => MentorshipProgram, { nullable: true })
  async mentorshipProgram(
    @graphql.Args() args: MentorshipProgramFindUniqueArgs
  ): Promise<MentorshipProgram | null> {
    const result = await this.service.mentorshipProgram(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MentorshipProgram)
  async deleteMentorshipProgram(
    @graphql.Args() args: DeleteMentorshipProgramArgs
  ): Promise<MentorshipProgram | null> {
    try {
      return await this.service.deleteMentorshipProgram(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
