/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MentorshipProgram } from "./MentorshipProgram";
import { MentorshipProgramCountArgs } from "./MentorshipProgramCountArgs";
import { MentorshipProgramFindManyArgs } from "./MentorshipProgramFindManyArgs";
import { MentorshipProgramFindUniqueArgs } from "./MentorshipProgramFindUniqueArgs";
import { DeleteMentorshipProgramArgs } from "./DeleteMentorshipProgramArgs";
import { MentorshipProgramService } from "../mentorshipProgram.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => MentorshipProgram)
export class MentorshipProgramResolverBase {
  constructor(
    protected readonly service: MentorshipProgramService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MentorshipProgram",
    action: "read",
    possession: "any",
  })
  async _mentorshipProgramsMeta(
    @graphql.Args() args: MentorshipProgramCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [MentorshipProgram])
  @nestAccessControl.UseRoles({
    resource: "MentorshipProgram",
    action: "read",
    possession: "any",
  })
  async mentorshipPrograms(
    @graphql.Args() args: MentorshipProgramFindManyArgs
  ): Promise<MentorshipProgram[]> {
    return this.service.mentorshipPrograms(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => MentorshipProgram, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MentorshipProgram",
    action: "read",
    possession: "own",
  })
  async mentorshipProgram(
    @graphql.Args() args: MentorshipProgramFindUniqueArgs
  ): Promise<MentorshipProgram | null> {
    const result = await this.service.mentorshipProgram(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MentorshipProgram)
  @nestAccessControl.UseRoles({
    resource: "MentorshipProgram",
    action: "delete",
    possession: "any",
  })
  async deleteMentorshipProgram(
    @graphql.Args() args: DeleteMentorshipProgramArgs
  ): Promise<MentorshipProgram | null> {
    try {
      return await this.service.deleteMentorshipProgram(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
