/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DiscussionForumService } from "../discussionForum.service";
import { DiscussionForumCreateInput } from "./DiscussionForumCreateInput";
import { DiscussionForum } from "./DiscussionForum";
import { DiscussionForumFindManyArgs } from "./DiscussionForumFindManyArgs";
import { DiscussionForumWhereUniqueInput } from "./DiscussionForumWhereUniqueInput";
import { DiscussionForumUpdateInput } from "./DiscussionForumUpdateInput";

export class DiscussionForumControllerBase {
  constructor(protected readonly service: DiscussionForumService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DiscussionForum })
  async createDiscussionForum(
    @common.Body() data: DiscussionForumCreateInput
  ): Promise<DiscussionForum> {
    return await this.service.createDiscussionForum({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [DiscussionForum] })
  @ApiNestedQuery(DiscussionForumFindManyArgs)
  async discussionForums(
    @common.Req() request: Request
  ): Promise<DiscussionForum[]> {
    const args = plainToClass(DiscussionForumFindManyArgs, request.query);
    return this.service.discussionForums({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DiscussionForum })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async discussionForum(
    @common.Param() params: DiscussionForumWhereUniqueInput
  ): Promise<DiscussionForum | null> {
    const result = await this.service.discussionForum({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DiscussionForum })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDiscussionForum(
    @common.Param() params: DiscussionForumWhereUniqueInput,
    @common.Body() data: DiscussionForumUpdateInput
  ): Promise<DiscussionForum | null> {
    try {
      return await this.service.updateDiscussionForum({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DiscussionForum })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDiscussionForum(
    @common.Param() params: DiscussionForumWhereUniqueInput
  ): Promise<DiscussionForum | null> {
    try {
      return await this.service.deleteDiscussionForum({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
