/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DiscussionForum } from "./DiscussionForum";
import { DiscussionForumCountArgs } from "./DiscussionForumCountArgs";
import { DiscussionForumFindManyArgs } from "./DiscussionForumFindManyArgs";
import { DiscussionForumFindUniqueArgs } from "./DiscussionForumFindUniqueArgs";
import { DeleteDiscussionForumArgs } from "./DeleteDiscussionForumArgs";
import { DiscussionForumService } from "../discussionForum.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DiscussionForum)
export class DiscussionForumResolverBase {
  constructor(
    protected readonly service: DiscussionForumService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DiscussionForum",
    action: "read",
    possession: "any",
  })
  async _discussionForumsMeta(
    @graphql.Args() args: DiscussionForumCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DiscussionForum])
  @nestAccessControl.UseRoles({
    resource: "DiscussionForum",
    action: "read",
    possession: "any",
  })
  async discussionForums(
    @graphql.Args() args: DiscussionForumFindManyArgs
  ): Promise<DiscussionForum[]> {
    return this.service.discussionForums(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DiscussionForum, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DiscussionForum",
    action: "read",
    possession: "own",
  })
  async discussionForum(
    @graphql.Args() args: DiscussionForumFindUniqueArgs
  ): Promise<DiscussionForum | null> {
    const result = await this.service.discussionForum(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DiscussionForum)
  @nestAccessControl.UseRoles({
    resource: "DiscussionForum",
    action: "delete",
    possession: "any",
  })
  async deleteDiscussionForum(
    @graphql.Args() args: DeleteDiscussionForumArgs
  ): Promise<DiscussionForum | null> {
    try {
      return await this.service.deleteDiscussionForum(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
