/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { EventRegistration } from "./EventRegistration";
import { EventRegistrationCountArgs } from "./EventRegistrationCountArgs";
import { EventRegistrationFindManyArgs } from "./EventRegistrationFindManyArgs";
import { EventRegistrationFindUniqueArgs } from "./EventRegistrationFindUniqueArgs";
import { CreateEventRegistrationArgs } from "./CreateEventRegistrationArgs";
import { UpdateEventRegistrationArgs } from "./UpdateEventRegistrationArgs";
import { DeleteEventRegistrationArgs } from "./DeleteEventRegistrationArgs";
import { Event } from "../../event/base/Event";
import { User } from "../../user/base/User";
import { EventRegistrationService } from "../eventRegistration.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => EventRegistration)
export class EventRegistrationResolverBase {
  constructor(
    protected readonly service: EventRegistrationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "EventRegistration",
    action: "read",
    possession: "any",
  })
  async _eventRegistrationsMeta(
    @graphql.Args() args: EventRegistrationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [EventRegistration])
  @nestAccessControl.UseRoles({
    resource: "EventRegistration",
    action: "read",
    possession: "any",
  })
  async eventRegistrations(
    @graphql.Args() args: EventRegistrationFindManyArgs
  ): Promise<EventRegistration[]> {
    return this.service.eventRegistrations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => EventRegistration, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "EventRegistration",
    action: "read",
    possession: "own",
  })
  async eventRegistration(
    @graphql.Args() args: EventRegistrationFindUniqueArgs
  ): Promise<EventRegistration | null> {
    const result = await this.service.eventRegistration(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => EventRegistration)
  @nestAccessControl.UseRoles({
    resource: "EventRegistration",
    action: "create",
    possession: "any",
  })
  async createEventRegistration(
    @graphql.Args() args: CreateEventRegistrationArgs
  ): Promise<EventRegistration> {
    return await this.service.createEventRegistration({
      ...args,
      data: {
        ...args.data,

        event: args.data.event
          ? {
              connect: args.data.event,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => EventRegistration)
  @nestAccessControl.UseRoles({
    resource: "EventRegistration",
    action: "update",
    possession: "any",
  })
  async updateEventRegistration(
    @graphql.Args() args: UpdateEventRegistrationArgs
  ): Promise<EventRegistration | null> {
    try {
      return await this.service.updateEventRegistration({
        ...args,
        data: {
          ...args.data,

          event: args.data.event
            ? {
                connect: args.data.event,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => EventRegistration)
  @nestAccessControl.UseRoles({
    resource: "EventRegistration",
    action: "delete",
    possession: "any",
  })
  async deleteEventRegistration(
    @graphql.Args() args: DeleteEventRegistrationArgs
  ): Promise<EventRegistration | null> {
    try {
      return await this.service.deleteEventRegistration(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Event, {
    nullable: true,
    name: "event",
  })
  @nestAccessControl.UseRoles({
    resource: "Event",
    action: "read",
    possession: "any",
  })
  async getEvent(
    @graphql.Parent() parent: EventRegistration
  ): Promise<Event | null> {
    const result = await this.service.getEvent(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(
    @graphql.Parent() parent: EventRegistration
  ): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
